"""Write migrations/0004_catalogue.sql: the catalogue and Kit Spec move from gear-data.json into D1 (spec §6).

One-off: after this migration the admin Items page is the source, and gear-data.json is kept only as a test fixture
(api/test/fixtures/gear-data-2026-10.json), which is what this script reads.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
data = json.loads((ROOT / "api/test/fixtures/gear-data-2026-10.json").read_text(encoding="utf-8"))
q = lambda v: "'" + str(v).replace("'", "''") + "'"
AT = "2026-10-11T00:00:00.000Z"

cats = {name: n + 1 for n, name in enumerate(data["categories"])}
cat_rows = ",\n".join(f"  ({cid}, {q(name)}, {cid * 10})" for name, cid in cats.items())

item_rows, seen = [], {}
for item in data["items"]:
    seen[item["category"]] = seen.get(item["category"], 0) + 10
    item_rows.append(f"  ({q(item['id'])}, {cats[item['category']]}, {q(item['name'])}, {seen[item['category']]}, 0, '{AT}')")

spec_ids = {name: n + 1 for n, name in enumerate(data["specs"])}
spec_rows = ",\n".join(f"  ({sid}, {q(name)}, {sid * 10})" for name, sid in spec_ids.items())
qty_rows = ",\n".join(
    f"  ({spec_ids[spec]}, {q(item)}, {qty})" for spec, items in data["specs"].items() for item, qty in items.items()
)

sql = f"""-- The catalogue and Kit Spec move into D1 so the admin Items page can edit them (docs/spec.md §2, §6).
-- Generated by scripts/catalogue_migration.py from the last gear-data.json.
CREATE TABLE categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, sort INTEGER NOT NULL);
CREATE UNIQUE INDEX categories_name ON categories (name COLLATE NOCASE);

CREATE TABLE items (
  id TEXT PRIMARY KEY,
  category_id INTEGER NOT NULL REFERENCES categories(id),
  name TEXT NOT NULL,
  sort INTEGER NOT NULL,
  retired INTEGER NOT NULL DEFAULT 0 CHECK (retired IN (0, 1)),
  created_at TEXT NOT NULL
);
CREATE UNIQUE INDEX items_name ON items (category_id, name COLLATE NOCASE);

CREATE TABLE kit_specs (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, sort INTEGER NOT NULL);
CREATE UNIQUE INDEX kit_specs_name ON kit_specs (name COLLATE NOCASE);

CREATE TABLE kit_spec_items (
  spec_id INTEGER NOT NULL REFERENCES kit_specs(id) ON DELETE CASCADE,
  item_id TEXT NOT NULL REFERENCES items(id),
  qty INTEGER NOT NULL CHECK (qty BETWEEN 1 AND 99),
  PRIMARY KEY (spec_id, item_id)
);

INSERT INTO categories (id, name, sort) VALUES
{cat_rows};

INSERT INTO items (id, category_id, name, sort, retired, created_at) VALUES
{",".join(chr(10) + r for r in item_rows)[1:]};

INSERT INTO kit_specs (id, name, sort) VALUES
{spec_rows};

INSERT INTO kit_spec_items (spec_id, item_id, qty) VALUES
{qty_rows};
"""
(ROOT / "migrations/0004_catalogue.sql").write_text(sql, encoding="utf-8", newline="\n")
print("wrote migrations/0004_catalogue.sql")
