"""Write migrations/0003_levels.sql: stocktakes -> levels + log (see docs/spec.md §6).

The Kit Spec and catalogue come from shared/src/gear-data.json and are loaded into helper tables that the
migration drops again. Rerun only if gear-data.json changes before this migration is applied.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
data = json.loads((ROOT / "shared/src/gear-data.json").read_text(encoding="utf-8"))
q = lambda v: "'" + str(v).replace("'", "''") + "'"

catalogue = ",\n".join(f"  ({q(i['id'])}, {q(i['name'])}, {n})" for n, i in enumerate(data["items"]))
kit = ",\n".join(f"  ({q(col)}, {q(item)}, {qty})" for col, items in data["specs"].items() for item, qty in items.items())

LATEST = """
  stocktakes s
  JOIN (SELECT team_slug, MAX(date) AS date FROM stocktakes GROUP BY team_slug) m ON m.team_slug = s.team_slug AND m.date = s.date
  JOIN lines l ON l.stocktake_id = s.id
  JOIN teams t ON t.slug = s.team_slug"""

sql = f"""-- Stocktakes become current levels plus a log of changes (docs/spec.md §6). Generated by scripts/levels_migration.py.
CREATE TABLE levels (
  team_slug TEXT NOT NULL,
  item_id TEXT NOT NULL,
  level INTEGER NOT NULL DEFAULT 0 CHECK (level >= 0),
  added INTEGER NOT NULL DEFAULT 0 CHECK (added IN (0, 1)),
  updated_at TEXT NOT NULL,
  PRIMARY KEY (team_slug, item_id)
);

CREATE TABLE log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  team_slug TEXT NOT NULL,
  item_id TEXT NOT NULL,
  item_name TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('opening', 'adjust', 'move', 'count')),
  change INTEGER NOT NULL,
  level_after INTEGER NOT NULL,
  move_id TEXT,
  from_slug TEXT,
  to_slug TEXT,
  note TEXT,
  who TEXT NOT NULL
);
CREATE INDEX log_team ON log (team_slug, id DESC);
CREATE INDEX log_team_item ON log (team_slug, item_id, id DESC);

CREATE TABLE mig_catalogue (item_id TEXT PRIMARY KEY, name TEXT NOT NULL, sort INTEGER NOT NULL);
INSERT INTO mig_catalogue (item_id, name, sort) VALUES
{catalogue};

CREATE TABLE mig_kit_spec (spec TEXT NOT NULL, item_id TEXT NOT NULL, qty INTEGER NOT NULL);
INSERT INTO mig_kit_spec (spec, item_id, qty) VALUES
{kit};

-- 1. Each team's latest stocktake becomes its levels.
INSERT INTO levels (team_slug, item_id, level, added, updated_at)
SELECT s.team_slug, l.item_id, l.count, l.added, s.created_at FROM {LATEST};

-- 2. Kit Spec items (teams) and every item (pools) are always listed.
INSERT OR IGNORE INTO levels (team_slug, item_id, level, added, updated_at)
SELECT t.slug, k.item_id, 0, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM teams t JOIN mig_kit_spec k ON k.spec = t.spec WHERE t.kind = 'team';
INSERT OR IGNORE INTO levels (team_slug, item_id, level, added, updated_at)
SELECT t.slug, c.item_id, 0, 0, strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM teams t CROSS JOIN mig_catalogue c WHERE t.kind = 'pool';

-- 3. Opening log entries for every level above 0.
INSERT INTO log (at, updated_at, team_slug, item_id, item_name, kind, change, level_after, who)
SELECT s.created_at, s.created_at, s.team_slug, l.item_id, l.name, 'opening', l.count, l.count, 'Migration'
FROM {LATEST}
WHERE l.count > 0
ORDER BY s.created_at, s.team_slug, l.sort;

-- 4. Done with stocktakes.
DROP TABLE lines;
DROP TABLE stocktakes;
DROP TABLE mig_kit_spec;
DROP TABLE mig_catalogue;
"""
(ROOT / "migrations/0003_levels.sql").write_text(sql, encoding="utf-8", newline="\n")
print("wrote migrations/0003_levels.sql")
